### ISSUE TITLE
ImportError: No module named pymysql

### ISSUE THREAD

**Issue by yanchenko-igor** [esnme/ultramysql#18]
setup.py need installed pymysql.

$ python setup.py install
Traceback (most recent call last):
  File "skiped/src/umysqldb/setup.py", line 3, in <module>
    from umysqldb import **version**
  File "skiped/src/umysqldb/umysqldb/**init**.py", line 2, in <module>
    import pymysql
ImportError: No module named pymysql

**Comment by yanchenko-igor** [comment]
sorry, it is umysqldb issue
